### ISSUE TITLE
node.js 를 설치한다.

### ISSUE THREAD

**Issue by headcha** [LEEHWIJIN/internsheep-back#4]
[요구사항]
1. web server 에 node.js 를 설치한다.
2. 버전은 최신 안정 버전을 사용한다.

[완료조건]
1. node.js 를 실행시킬 수 있다.
2. node -v 으로 설치 여부를 확인할 수 있다.

**Comment by LEEHWIJIN** [comment]
node -v : v10.15.3
npm -v : 6.4.1

@hol819 , @SUYEON97
